spring:
  application:
    name: turbin
server:
  port: 5001
turbine:
  app-config: feign,order-service
  cluster-name-expression: new String("default")  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
