spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.177.128
    port: 5672
    username: admin
    password: admin 
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
#默认配置能找到微服务名字,所以说可以不配置
routes:
  item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**

#开启重试
zuul:
  retryable: true
    
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 2000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
#整合zuul+hystrix短路
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
#暴露端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
#整合turbine聚合监控
turbine:
  app-config: order-service,zuul
  cluster-name-expression: new String("default")
  
